### ISSUE TITLE
Výběr platformy

### ISSUE THREAD

**Issue by awetails** [mlienhart/Zeus#1]
Na jaké platformě to ideálně postavit?

**Comment by awetails** [comment]
Teda předpokládám, že to bude hlavně webové... nevidím moc smysl v alternativách pro aplikaci tohoto typu

**Comment by mlienhart** [comment]
Jsem pro softwarove reseni ve forme webove aplikace.

**Comment by murban27** [comment]
Určitě WEB, desktop nemá smysl.

Navrhoval bych osobně WP - požadavky přesně odpovídají tomu, proč vůbec WP existuje :)
Server máme na linuxu, kde je ještě alternativa PHP:

**Comment by awetails** [comment]
No já bych se osobně stavěl také za WP, ale nutno dodat že je nutné zvážit projektové a a administrativní požadavky... osobně si třeba nejsem vůbec jistý jakým způsobem udržovat na githubu WP aplikaci před nasazením... Koneckonců myšlenka CMS je jednoduchá, řekněme naklikávací, administrace.... A parametry se udržují v DB takže spíše nevhodné pro git....

**Comment by mlienhart** [comment]
Redakcni system WordPress je urcite vhodnym kandidatem na nas projekt Zeus. Pokud ma nekdo alternativni reseni, klidne piste.

**Comment by awetails** [comment]
> Redakcni system WordPress je urcite vhodnym kandidatem na nas projekt Zeus. Pokud ma nekdo alternativni reseni, klidne piste.

No jak pisu vhodne jke to pro aplikaci ale nejsem si jisty jestli je to vhodne kvuli tomu co mame delat v predmetu

**Comment by awetails** [comment]
No nejspi to nemusime resit... deployment aplikace rposte doresime pozdeji a v repository si proste budeme drzet soucasnou verzi dle momentalniho nastaveni...
