### ISSUE TITLE
UML diagramy

### ISSUE THREAD

**Issue by mlienhart** [mlienhart/Zeus#2]
Poud zbyte cas v projektu, muzeme pridat UML diagramy. Aktualne mam ale informaci, ze nejsou povinnou soucasti projektu.

**Comment by JindrichJansaRSP** [comment]
Uz mam hotovy use case diagram a activity diagram pro proces publikace clanku. Pokud to usnadni dalsi postup, tak pripravim i dalsi podle potreby.

**Comment by mlienhart** [comment]
Jasne, urcite se to hodi. Hod to Jindro sem na GitHub, at se na to podivame. Dik.

**Comment by mlienhart** [comment]
Zaloz slozku s nazem 'UML diagramy' a tam nahaz vsechno co mas. Dik.

**Comment by JindrichJansaRSP** [comment]
Nahrál jsem zatím oba diagramy. Podívejte se na to. Požívám neregistrovanou verzi starUML, tak proto ten background.
